---

- hosts: all
  user: vagrant
  sudo: true

  # vars:
  #   PORT_NUM: 6543

  tasks:

    - name: WHOAMI registering
      command: whoami sudo: false
        register: whoami

  #   # by having a tag we can narrow down a specific group of tasks
  #   # during configuration.
    - name: update cache / upgrade pkgs
      apt: update_cache=yes upgrade=dist
      tags:
        - apt
## sudo apt-get install nginx-full php5-fpm php5-cli php5-mcrypt php5-mysql mysql-server dnsmasq

  #   # combined install of these packages as vagrant reconnects for each task (this should speed things up!)
    - name: install dev pkgs / EMP stack
      apt: pkg=$item
      with_items:
        # - build-essential
        # - linux-generic 
        # - python-dev
        # - libevent-dev
        # - python-pip
        # - python-apt
        # - python-setuptools
        - curl
        - vim
        - git-core
        - mysql-server
        - mysql-client
        - nginx
        - php5-fpm
        - php5-mysql
        # - php5-cli
        # - php5-mcrypt
        # - dnsmasq
      tags:
        - apt
        - mysql
        - nginx
        - php

    # - name: install mysql/nginx/php (EMP stack)
    #   apt: pkg=$item
    #   with_items:
    #      - mysql-server
    #      - mysql-client
    #      - nginx
    #      - php5-fpm 
    #      - php5-mysql
    #   tags:
    #     - mysql
    #     - nginx

    # - name: pip install stuff
    #   pip: name=$item
    #   with_items:
    #      - distribute
    #      - virtualenv
         # - ansible

    # - name: configure nginx default
    #   template: src=configs/nginx-conf/default.j2 dest=/etc/nginx/sites-available/default
    #   tags:
    #     - nginx

    # - name: install mysql
    #   command: mysql_secure_installation
    #   tags:
    #     - mysql

          # # VirtualBox - http://www.virtualbox.org
          # # Run this command: wget -q http://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc -O- | sudo apt-key add -
            #  deb http://download.virtualbox.org/virtualbox/debian precise contrib


      # - name: set up php-fpm
      #   command: cp /etc/php5/fpm/pool.d/www.conf /var/www/$WHOAMI/conf/php5-fpm-pool.conf
      #   command: mv /etc/php5/fpm/pool.d/www.conf /etc/php5/fpm/pool.d/www.conf.off
      #   command: ln -s /var/www/$WHOAMI/conf/php5-fpm-pool.conf /etc/php5/fpm/pool.d/$WHOAMI.conf
      #   tags:
      #     - php-fpm


      # - name: install mysql
      #   action: shell mysql_secure_installation sudo=true
      #   tags:
      #     - mysql

              # this doesn't work yet
        # - name: change root password
        #   user: name=root password="password"

      # - name: Ensure vagrant user is allowed to sudo
        # lineinfile: dest={{ sudoers_path }} create=yes regexp="vagrant"
        # line="vagrant ALL=NOPASSWD:ALL" state=present



    - name: set up working directory
      command: mkdir -p /var/www/{$whoami.stdout}/public/
      tags:
        - mysql


        ## this nginx configuring is untested, comment out if destruction ensues
    - name: nginx configuring
      command: cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.orig
      command: sudo sed -i '/index index.html index.htm;/c\index index.html index.htm index.php;' /etc/nginx/sites-available/default
      command: sudo echo "location ~ .php$ { fastcgi_split_path_info ^(.+.php)(/.+)$; fastcgi_pass unix:/var/run/php5-fpm.sock; fastcgi_index index.php; include fastcgi_params; }" /etc/nginx/sites-available/default
      tags:
        - nginx

    - name: enable php-fpm socket
      command: cp /etc/php5/fpm/pool.d/www.conf /etc/php5/fpm/pool.d/www.conf.orig
      command: sudo sed -i '/listen = 127.0.0.1:9000/c\listen = \/var\/run\/php5-fpm.sock' /etc/php5/fpm/pool.d/www.conf
      tags:
        - php


    - name: install composer/pomander
      command: curl -s https://getcomposer.org/installer | php
      command: sudo mv composer.phar /usr/local/bin/composer
      command: composer global require pomander/pomander:@stable
      command: echo 'export PATH="$HOME/.composer/vendor/bin:$PATH"' >> ~/.bashrc
      tags:
        - pomander




    - name: restart nginx
      service: name=nginx state=restarted
      tags:
        - nginx


    - name: restart php-fpm
      service: name=php5-fpm state=restarted
      tags:
        - php

