---

  - name: install mysql
    apt: pkg={{ item }}
    with_items:
      - mysql-server
      - python-mysqldb
    tags:
      - mysql

  - name: copy .my.cnf file with root password credentials
    template: src=my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600
