---

- hosts: all
  user: vagrant
  sudo: True

  # vars:
  #   PORT_NUM: 6543

  tasks:

  #   # by having a tag we can narrow down a specific group of tasks
  #   # during configuration.
    - name: update cache / upgrade pkgs
      apt: update_cache=yes upgrade=dist
      tags:
        - apt

  #   # combined install of these packages as vagrant reconnects for each task (this should speed things up!)
    - name: install dev pkgs / EMP stack
      apt: pkg=$item
      with_items:
        - build-essential
        - python-dev
        - libevent-dev
        - python-pip
        - python-apt
        - python-setuptools
        - curl
        - vim
        - git-core
        - nginx
        - mysql-server
        - mysql-client
        - php5
        - php5-cgi
        - php5-fpm 
        - php5-mysql
      tags:
        - apt
        - mysql
        - nginx

    # - name: install mysql/nginx/php (EMP stack)
    #   apt: pkg=$item
    #   with_items:
    #      - mysql-server
    #      - mysql-client
    #      - nginx
    #      - php5-fpm 
    #      - php5-mysql
    #   tags:
    #     - mysql
    #     - nginx

    - name: pip install stuff
      pip: name=$item
      with_items:
         - distribute
         - virtualenv
         # - ansible

    # - name: configure nginx default
    #   template: src=nginx-conf/default.j2 dest=/etc/nginx/sites-available/default
    #   tags:
    #     - nginx

    - name: restart nginx
      service: name=nginx state=restarted
      tags:
        - nginx

        # this doesn't work yet
    # - name: change root password
    #   user: name=root password="password"

    # - name: Ensure vagrant user is allowed to sudo
      # lineinfile: dest={{ sudoers_path }} create=yes regexp="vagrant"
      # line="vagrant ALL=NOPASSWD:ALL" state=present